# Используем базовый образ Python
FROM python:3.8

# Установка переменной окружения для отключения вывода байт-кодирования
ENV PYTHONUNBUFFERED 1

# Создание директории для приложения и установка рабочей директории
RUN mkdir /app
WORKDIR /app

# Копируем файлы зависимостей и устанавливаем их
COPY requirements.txt /app/
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы приложения в контейнер
COPY . /app/

# Установка переменной окружения для файла .env
ENV DJANGO_SETTINGS_MODULE=news_parser_project.settings
#RUN pip install --no-cache-dir gunicorn
# Запуск Gunicorn для вашего приложения
#CMD ["python manage.py makemigration\
 #           && python manage.py migrate"]
