# Generated by Django 3.1.13 on 2023-09-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField()),
                ('post_title', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField()),
                ('post_text', models.TextField()),
                ('post_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
